[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "win"
path = "src/main.rs"

[[bin]]
name = "winstack"
path = "src/bin/winstack.rs"

[[bin]]
name = "winopen"
path = "src/bin/winopen.rs"

[dependencies]
canon-types = { workspace = true }
winstack-crypto = { workspace = true }
identity-core = { workspace = true }
time-core = { workspace = true }
policy-core = { workspace = true }
object-store = { workspace = true }
graph-index = { workspace = true }
verifier = { workspace = true }
registry-core = { workspace = true }
module-import = { workspace = true }
module-ai = { workspace = true }
window-api = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
win-format = { path = "../win-format" }
clap = { workspace = true }
tokio = { workspace = true }
base64 = { workspace = true }
ureq = { workspace = true }
